multipleSolar_shadow_angles(spatialpoint_list = deBilt.sf, name_list = c("De Bilt"),
                            sensor.name = temperature_sensor_name,
                            name.supplement = "__", AWS = TRUE,
                            solar_angles = TRUE, angle_selection_byIndexNr = c(37, 38),
                            calculate_shadow_angles = TRUE,
                            sensor_height = 0,
                            read_only_shadow_values = FALSE,
                            extract_method = 'bilinear',
                            years = c(2018),
                            months = c(12, 1:6),
                            days = c(21),
                            s_hour = 0,
                            f_hour = 23,
                            minutes.interval = 15,
                            radius = 100,
                            AHN3 = TRUE,
                            full_circle_mask = FALSE,
                            printChart = FALSE,
                            exportCSV = TRUE,
                            test = FALSE)
